<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.0.1</Version>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>AC.Converter.MarkdownToBBCode.Shared</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <Title>Markdown To BBCode Shared</Title>
        <Authors>Aragas;MIRIMIR</Authors>
        <Company>AmusementClub (fork from BUTR)</Company>
        <Description>Converts Markdown to BBCode flavor. This is a fork of the original package developed by Aragas (BUTR)</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>markdown bbcode</PackageTags>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
        <PackageReference Include="Markdig" Version="0.40.0" />
    </ItemGroup>

</Project>
